fix 'invalid cross-device link' error
Previously cleaning golden files would involve moving them into a tmp dir, which could fail
if the tmp dir and testdata dir are not on the same device per #20

```
❯ go test -update                                                                                                                                                         2021-03-16 15:19:44
--- FAIL: Test_WorstScores_nilResult (0.00s)
    autogold.go:82: rename testdata/nil.golden /tmp/go-golden-074934610/nil.golden: invalid cross-device link
FAIL
exit status 1
FAIL    <pkg name redacted>  0.006s
```

This changes the tmp dir we use to be the same path as the testdata dir, plus a `.autogold.tmp`
extension - so it is always on the same device.

Fixes #20

Signed-off-by: Stephen Gutekanst <stephen@hexops.com>